/*
Grokking: https://www.educative.io/courses/grokking-the-coding-interview/NEOZDEg5PlN

Given a word, write a function to generate all of its unique generalized abbreviations.

Generalized abbreviation of a word can be generated by replacing each substring of
the word by the count of characters in the substring. Take the example of “ab”
which has four substrings: “”, “a”, “b”, and “ab”. After replacing these
substrings in the actual word by the count of characters we get all the
generalized abbreviations: “ab”, “1b”, “a1”, and “2”.
*/

function generateGeneralizedAbbreviation(word) {
  const result = [];
  (function abbrevGenerator(current, start, count) {
    if (start === word.length) {
      if (count !== 0) {
        current += count;
      }
      result.push(current);
      return;
    }

    abbrevGenerator(current, start + 1, count + 1);

    if (count !== 0) current += count;

    current += word[start];

    abbrevGenerator(current, start + 1, 0);
  })('', 0, 0);

  return result;
}

/*
Time O(N * 2^N)
Space O(N * 2^N)
*/